### ISSUE TITLE
AttributeError on push

### ISSUE THREAD

**Issue by pbx** [guillermooo/Mercurial#4]
ST3, Linux 14.04, hg 2.82. Other commands working as expected.

When I choose 'push' from the SublimeHg menu, "Mercurial: Error" appears in the status bar and this appears in the console:

``` pytb
Exception in thread Thread-542:
Traceback (most recent call last):
  File "mercurial in /home/cmg/.config/sublime-text-3/Installed Packages/Mercurial.sublime-package", line 129, in run
  File "mercurial in /home/cmg/.config/sublime-text-3/Installed Packages/Mercurial.sublime-package", line 82, in run_in_console
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'lxterminal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "mercurial in /home/cmg/.config/sublime-text-3/Installed Packages/Mercurial.sublime-package", line 132, in run
AttributeError: 'FileNotFoundError' object has no attribute 'message'
```

**Comment by pbx** [comment]
Figured it out. The problem is that the default for `packages.mercurial.terminal` is lxterminal (which I do not have installed). I changed it to use an installed terminal program and the error went away.

I'll open a documentation issue when I have a moment, so this can be clarified and not trip up other people who don't have lxterminal installed.
